name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  UV_VERSION: 0.11.6
  UV_NO_SYNC: 1
  UV_LOCKED: 1
  PY_COLORS: 1

jobs:
  ci:
    runs-on: "${{ matrix.platform }}-latest"
    strategy:
      fail-fast: false
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python: ["3.10", "3.14"]
        platform: ["ubuntu", "macos", "windows"]
        include:
        - python: "3.11"
          platform: "ubuntu"
        - python: "3.12"
          platform: "ubuntu"
        - python: "3.13"
          platform: "ubuntu"
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false
    - name: Setup uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Environment
      id: sync
      run: uv sync

    - name: ruff format (Python formatting)
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff format --diff
    - name: ruff lint
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff check --output-format github
    - name: mypy
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run mypy --strict src tests
    - name: pytest
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run pytest -vv tests
