name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PY_COLORS: 1

jobs:
  ci:
    runs-on: "${{ matrix.platform }}-latest"
    environment: "Test"
    strategy:
      fail-fast: false
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python: ["3.8", "3.12"]
        platform: ["ubuntu", "macos", "windows"]
        include:
        - python: "3.9"
          platform: "ubuntu"
        - python: "3.10"
          platform: "ubuntu"
        - python: "3.11"
          platform: "ubuntu"
        - python: "pypy3.10"
          platform: "ubuntu"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python }}
    - uses: hynek/setup-cached-uv@v1
    - name: Install project
      run: |
        uv venv
        uv pip install . -r dev-requirements.txt
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Run tests
      run: python -m pytest
    - name: Lint code
      if: always()
      run: |
        ruff check
        ruff format --check
    - name: Run mypy
      if: always()
      run: mypy --strict crossandra tests